import { strict as assert } from "node:assert";
import test from "node:test";
import { parseGitCommand } from "../commands/gitCommandParser";
import type { RepositoryState } from "./repositoryState";
import { formatGoalCommand, rankedGoals, resolveGoal } from "./goal";

const id = "a".repeat(40); const head = { id, shortId: "aaaaaaa", subject: "head" };
const state = (overrides: Partial<RepositoryState> = {}): RepositoryState => ({ repository: { rootPath: "/repo" }, currentLocation: { kind: "branch", branchName: "main", head, detached: false }, localBranches: [{ name: "main", tipCommitId: id }, { name: "feature", tipCommitId: id }], workingTree: { staged: [], unstaged: [], untracked: [], conflicts: [] }, history: [{ commit: head, parentIds: [] }], operation: { kind: "normal" }, remotes: { kind: "available", value: [{ name: "upstream", trackingRefs: [{ branchName: "main", trackingRef: "refs/remotes/upstream/main", commitId: id }], locallyKnownDefaultBranch: null }] }, upstream: { kind: "notConfigured" }, stash: { kind: "available", value: [] }, comparison: { kind: "notConfigured" }, stateVersion: 1, refreshedAt: new Date(0), ...overrides });

test("goals are pure, state-aware, and never recommend dangerous commands", () => { const input = state({ workingTree: { staged: [], unstaged: [{ path: "a", kind: "modified" }], untracked: [], conflicts: [] } }); const before = structuredClone(input); const add = resolveGoal(input, { goalId: "stageChanges" }); const commit = resolveGoal(input, { goalId: "commitChanges" }); assert.equal(add.primary?.steps[0]?.command.kind, "add"); assert.equal(commit.primary?.steps.length, 2); assert.deepEqual(input, before); assert.equal(JSON.stringify(commit).includes("reset"), false); assert.ok(rankedGoals(input).includes("stageChanges")); });
test("targets, already-satisfied states, stash, fetch and formatter round-trip stay factual", () => { assert.equal(resolveGoal(state(), { goalId: "commitChanges" }).outcome, "noOperationNeeded"); const stash = resolveGoal(state({ stash: { kind: "available", value: [{ index: 0, commitId: id, message: "wip" }] } }), { goalId: "restoreStash" }); assert.equal(stash.primary?.steps[0]?.command.kind, "stashApply"); assert.equal(stash.alternative?.steps[0]?.command.kind, "stashPop"); const fetch = resolveGoal(state(), { goalId: "fetchRemote" }); const command = fetch.primary?.steps[0]?.command; assert.ok(command); assert.deepEqual(parseGitCommand(formatGoalCommand(command!)), { kind: "parsed", command }); assert.equal(resolveGoal(state({ remotes: { kind: "unavailable", reason: "no" } }), { goalId: "fetchRemote" }).outcome, "unsupported"); });
