import type { GitCommand } from "./gitCommand";
import type { RepositoryState } from "./repositoryState";

export type GoalId = "stageChanges" | "commitChanges" | "stashChanges" | "pushCommits" | "fetchRemote" | "pullRemote" | "mergeBase" | "rebaseBase" | "switchBranch" | "createBranch" | "switchWithWork" | "unstageChanges" | "restoreStash";
export type GoalCategory = "save" | "integrate" | "workElsewhere" | "undo";
export type GoalTarget = { readonly kind: "branch"; readonly branchName: string } | { readonly kind: "remote"; readonly remote: string } | { readonly kind: "remoteBranch"; readonly remote: string; readonly branch: string } | { readonly kind: "newBranch"; readonly branchName: string };
export interface GoalRequest { readonly goalId: GoalId; readonly target?: GoalTarget; }
export interface GoalStep { readonly id: string; readonly command: GitCommand; readonly afterPrevious?: boolean; }
export interface GoalRecommendation { readonly kind: "primary" | "alternative"; readonly label: string; readonly advanced?: boolean; readonly steps: readonly GoalStep[]; }
export type GoalResolution = { readonly goalId: GoalId; readonly label: string; readonly category: GoalCategory; readonly current: string; readonly change: string; readonly outcome: "recommended" | "needsTarget" | "needsInput" | "noOperationNeeded" | "blocked" | "unsupported"; readonly primary?: GoalRecommendation; readonly alternative?: GoalRecommendation; readonly targetChoices?: readonly GoalTarget[]; readonly notice?: string; };

export const goalCatalog: readonly { readonly id: GoalId; readonly category: GoalCategory; readonly label: string }[] = [
  { id: "stageChanges", category: "save", label: "次のcommitに今の変更を入れたい" }, { id: "commitChanges", category: "save", label: "commitとして残したい" }, { id: "stashChanges", category: "save", label: "変更を一時的に退避したい" }, { id: "pushCommits", category: "save", label: "local commitをRemoteへ送りたい" },
  { id: "fetchRemote", category: "integrate", label: "Remoteの新しい情報を確認したい" }, { id: "pullRemote", category: "integrate", label: "Remote側の変更を今のbranchへ取り込みたい" }, { id: "mergeBase", category: "integrate", label: "基準branchの変更を今のbranchへ取り込みたい" }, { id: "rebaseBase", category: "integrate", label: "自分のcommitを基準branchの後ろに並べ直したい" },
  { id: "switchBranch", category: "workElsewhere", label: "既存の別branchへ移りたい" }, { id: "createBranch", category: "workElsewhere", label: "新しいbranchを作って移りたい" }, { id: "switchWithWork", category: "workElsewhere", label: "作業途中の変更を持って別branchへ移りたい" },
  { id: "unstageChanges", category: "undo", label: "Stagingへ入れた変更を外したい" }, { id: "restoreStash", category: "undo", label: "Stashへ退避した作業を戻したい" },
];

const meta = (id: GoalId) => goalCatalog.find((item) => item.id === id)!;
const step = (id: string, command: GitCommand, afterPrevious = false): GoalStep => ({ id, command, ...(afterPrevious ? { afterPrevious: true } : {}) });
const recommendation = (kind: "primary" | "alternative", label: string, steps: readonly GoalStep[], advanced = false): GoalRecommendation => ({ kind, label, steps, ...(advanced ? { advanced: true } : {}) });
const result = (id: GoalId, current: string, change: string, outcome: GoalResolution["outcome"], extra: Partial<GoalResolution> = {}): GoalResolution => ({ goalId: id, label: meta(id).label, category: meta(id).category, current, change, outcome, ...extra });
const dirty = (state: RepositoryState) => state.workingTree.staged.length + state.workingTree.unstaged.length + state.workingTree.untracked.length > 0;
const currentBranch = (state: RepositoryState) => state.currentLocation.kind === "branch" ? state.currentLocation.branchName : undefined;
const remotes = (state: RepositoryState) => state.remotes.kind === "available" ? state.remotes.value.map((item) => ({ kind: "remote" as const, remote: item.name })).filter((item) => safe(item.remote)) : [];
const safe = (value: string) => value.length > 0 && value.length <= 256 && !value.startsWith("-") && !/[\r\n]/.test(value);
const branchChoices = (state: RepositoryState) => state.localBranches.filter((item) => item.name !== currentBranch(state) && safe(item.name)).map((item) => ({ kind: "branch" as const, branchName: item.name }));
const knownBase = (state: RepositoryState): string | undefined => { if (state.comparison.kind !== "available") return undefined; const ref = state.comparison.value.baseRef; const local = state.localBranches.find((item) => `refs/heads/${item.name}` === ref && safe(item.name)); if (local) return local.name; if (state.remotes.kind !== "available") return undefined; const known = state.remotes.value.flatMap((remote) => remote.trackingRefs.map((tracking) => ({ remote, tracking }))).find(({ remote, tracking }) => tracking.trackingRef === ref && safe(`${remote.name}/${tracking.branchName}`)); return known ? `${known.remote.name}/${known.tracking.branchName}` : undefined; };

export function resolveGoal(state: RepositoryState, request: GoalRequest): GoalResolution {
  const id = request.goalId; if (state.workingTree.conflicts.length) return result(id, "未解決のconflictがあります。", "安全に操作を案内できません。", "blocked"); if (state.operation.kind !== "normal") return result(id, "別のGit処理の途中です。", "現在のSimulatorではこの操作を扱いません。", "unsupported");
  const staged = state.workingTree.staged.length > 0; const unstaged = state.workingTree.unstaged.length > 0 || state.workingTree.untracked.length > 0;
  if (id === "stageChanges") return unstaged ? result(id, "まだStagingへ入っていない変更があります。", "変更をStagingへ記録します。", "recommended", { primary: recommendation("primary", "変更をStagingへ入れる", [step("add", { kind: "add", target: { kind: "repositoryRoot" } })]) }) : result(id, "追加でStagingへ入れる変更はありません。", "操作は不要です。", "noOperationNeeded");
  if (id === "unstageChanges") return staged ? result(id, "Stagingに変更があります。", "Stagingから外します。", "recommended", { primary: recommendation("primary", "Stagingから外す", [step("unstage", { kind: "unstage", syntax: "restoreStaged", paths: ["."] })]) }) : result(id, "Stagingは空です。", "操作は不要です。", "noOperationNeeded");
  if (id === "commitChanges") return staged ? result(id, "Stagingにcommitできる変更があります。", "新しいcommitを作ります。", "recommended", { primary: recommendation("primary", "commitを作る", [step("commit", { kind: "commit" })]), notice: "commit messageはGitで入力します。" }) : unstaged ? result(id, "まだStagingへ入っていない変更があります。", "Stagingへ記録してからcommitを作ります。", "recommended", { primary: recommendation("primary", "変更を残す", [step("add", { kind: "add", target: { kind: "repositoryRoot" } }), step("commit", { kind: "commit" }, true)]), notice: "2番目の手順は、前の手順を実際に行いRefreshしてからPreviewしてください。" }) : result(id, "commitする変更はありません。", "操作は不要です。", "noOperationNeeded");
  if (id === "stashChanges") return dirty(state) ? result(id, "作業中の変更があります。", "変更をStash Shelfへ退避します。", "recommended", { primary: recommendation("primary", "一時的に退避", [step("stash", { kind: "stashPush", includeUntracked: state.workingTree.untracked.length > 0 })]) }) : result(id, "退避する変更はありません。", "操作は不要です。", "noOperationNeeded");
  if (id === "restoreStash") { if (state.stash.kind !== "available") return result(id, "Stash情報を取得できません。", "entry数を断定できません。", "unsupported"); return state.stash.value.length ? result(id, "Stash Shelfにentryがあります。", "変更を作業場所へ適用します。", "recommended", { primary: recommendation("primary", "entryを残して適用", [step("apply", { kind: "stashApply", stashIndex: 0 })]), alternative: recommendation("alternative", "成功後にentryも削除", [step("pop", { kind: "stashPop", stashIndex: 0 })]) }) : result(id, "Stash Shelfは空です。", "操作は不要です。", "noOperationNeeded"); }
  if (id === "fetchRemote") { if (state.remotes.kind === "notConfigured") return result(id, "Remoteは設定されていません。", "接続先を推測しません。", "blocked"); if (state.remotes.kind === "unavailable") return result(id, "Remote情報を取得できません。", "接続先を断定できません。", "unsupported"); const choices = remotes(state); const requested = request.target?.kind === "remote" ? request.target : undefined; const target = requested && choices.some((item) => item.remote === requested.remote) ? requested : choices.length === 1 ? choices[0] : undefined; return target ? result(id, `${target.remote} は現在のFactで確認できます。`, "ローカルに記録されたRemote情報を更新します。", "recommended", { primary: recommendation("primary", "情報を取得", [step("fetch", { kind: "fetch", remote: target.remote })]) }) : result(id, "複数のRemoteがあります。", "対象を選んでください。", "needsTarget", { targetChoices: choices }); }
  if (id === "switchBranch" || id === "switchWithWork") { const choices = branchChoices(state); const requested = request.target?.kind === "branch" ? request.target : undefined; const target = requested && choices.some((item) => item.branchName === requested.branchName) ? requested : choices.length === 1 ? choices[0] : undefined; if (!target) return result(id, choices.length ? "移動先のbranchを選んでください。" : "移動できる別branchがありません。", "Factにないbranchは作りません。", choices.length ? "needsTarget" : "noOperationNeeded", { ...(choices.length ? { targetChoices: choices } : {}) }); const move = step("switch", { kind: "switch", branchName: target.branchName, create: false }, dirty(state)); return id === "switchWithWork" && dirty(state) ? result(id, "作業中の変更があります。", "退避してbranchを移り、変更を戻します。", "recommended", { primary: recommendation("primary", "作業を持って移る", [step("stash", { kind: "stashPush", includeUntracked: state.workingTree.untracked.length > 0 }), move, step("apply", { kind: "stashApply", stashIndex: 0 }, true)]), notice: "後続手順は前の手順を実際に行いRefreshしてからPreviewしてください。" }) : result(id, "移動先branchは現在のFactで確認できます。", "branchを切り替えます。", "recommended", { primary: recommendation("primary", "branchを移る", [move]) }); }
  if (id === "createBranch") { const name = request.target?.kind === "newBranch" ? request.target.branchName : undefined; if (!name) return result(id, "作成するbranch名を入力してください。", "新しいbranchを作って切り替えます。", "needsInput"); if (!safe(name) || state.localBranches.some((item) => item.name === name)) return result(id, "そのbranch名は現在のFactでは使えません。", "別の名前が必要です。", "blocked"); return result(id, "新しいbranch名が入力されています。", "branchを作って切り替えます。", "recommended", { primary: recommendation("primary", "新しいbranchへ移る", [step("create", { kind: "switch", branchName: name, create: true })]) }); }
  if (id === "mergeBase" || id === "rebaseBase") { const base = knownBase(state); if (state.comparison.kind !== "available" || !base) return result(id, "基準branchを現在のFactから解決できません。", "mainなどを推測しません。", "unsupported"); const relation = state.comparison.value; if (relation.behind === 0 || (id === "rebaseBase" && relation.ahead === 0)) return result(id, "この目的のために取り込む・再生成するcommitはありません。", "操作は不要です。", "noOperationNeeded"); if (id === "mergeBase") return result(id, "基準branch側に取り込む変更があります。", "履歴を統合します。", "recommended", { primary: recommendation("primary", "基準branchを統合", [step("merge", { kind: "merge", branch: base })]), ...(relation.ahead > 0 ? { alternative: recommendation("alternative", "commitを並べ直す", [step("rebase", { kind: "rebase", upstream: base })], true) } : {}) }); return result(id, "基準branchの後ろへ並べ直せます。", "自分のcommitを再生成します。", "recommended", { primary: recommendation("primary", "commitを並べ直す", [step("rebase", { kind: "rebase", upstream: base })], true) }); }
  if (id === "pullRemote") { const upstream = state.upstream.kind === "available" && state.upstream.value.remoteName !== "." && safe(state.upstream.value.remoteName) && safe(state.upstream.value.branchName) ? { kind: "remoteBranch" as const, remote: state.upstream.value.remoteName, branch: state.upstream.value.branchName } : undefined; const choices = upstream ? [upstream] : state.remotes.kind === "available" ? state.remotes.value.flatMap((remote) => remote.trackingRefs.filter((ref) => safe(remote.name) && safe(ref.branchName)).map((ref) => ({ kind: "remoteBranch" as const, remote: remote.name, branch: ref.branchName }))) : []; const requested = request.target?.kind === "remoteBranch" ? request.target : undefined; const target = requested && choices.some((item) => item.remote === requested.remote && item.branch === requested.branch) ? requested : choices.length === 1 ? choices[0] : undefined; return target ? result(id, `${target.remote}/${target.branch} は現在のFactで確認できます。`, "fetchしてから統合します。", "recommended", { primary: recommendation("primary", "Remote側を取り込む", [step("pull", { kind: "pull", target: { kind: "explicit", remote: target.remote, branch: target.branch }, rebase: false })]), alternative: recommendation("alternative", "rebaseで取り込む", [step("pullRebase", { kind: "pull", target: { kind: "explicit", remote: target.remote, branch: target.branch }, rebase: true })], true) }) : result(id, "取り込むRemote branchを現在のFactから選べません。", "default pull先を推測しません。", choices.length ? "needsTarget" : "unsupported", { ...(choices.length ? { targetChoices: choices } : {}) }); }
  if (id === "pushCommits") { const branch = currentBranch(state); if (!branch) return result(id, "detached HEADでは通常のpushを案内しません。", "branchを確認してください。", "blocked"); if (state.upstream.kind === "available" && state.upstream.value.remoteName !== ".") { const relation = state.upstream.value.relation; if (relation.kind === "available" && relation.value.ahead === 0) return result(id, "last-fetched Fact上でlocal-only commitはありません。", "操作は不要です。", "noOperationNeeded"); return result(id, "upstreamが設定されています。", "local commitをRemoteへ送信します。", "recommended", { primary: recommendation("primary", "pushする", [step("push", { kind: "push", target: { kind: "default" }, setUpstream: false })]) }); } if (state.remotes.kind !== "available") return result(id, "Remoteを現在のFactから選べません。", "接続先を推測しません。", "unsupported"); const choices = remotes(state); const requested = request.target?.kind === "remote" ? request.target : undefined; const target = requested && choices.some((item) => item.remote === requested.remote) ? requested : choices.length === 1 ? choices[0] : undefined; return target ? result(id, `${target.remote} は現在のFactで確認できます。`, "upstreamを設定して送信します。", "recommended", { primary: recommendation("primary", "upstreamを設定してpush", [step("push", { kind: "push", target: { kind: "explicit", remote: target.remote, branch }, setUpstream: true })]) }) : result(id, "送信先Remoteを選んでください。", "接続先を推測しません。", "needsTarget", { targetChoices: choices }); }
  return result(id, "現在の状態を確認してください。", "操作を案内できません。", "unsupported");
}

export function rankedGoals(state: RepositoryState): readonly GoalId[] { const values: GoalId[] = []; if (state.workingTree.staged.length) values.push("commitChanges"); if (state.workingTree.unstaged.length || state.workingTree.untracked.length) values.push("stageChanges"); if (dirty(state) && branchChoices(state).length) values.push("switchWithWork"); if (state.comparison.kind === "available" && state.comparison.value.behind > 0) values.push("mergeBase"); if (state.upstream.kind === "available" && state.upstream.value.relation.kind === "available" && state.upstream.value.relation.value.ahead > 0) values.push("pushCommits"); if (state.stash.kind === "available" && state.stash.value.length && !dirty(state)) values.push("restoreStash"); return [...new Set(values)].slice(0, 3); }

export function formatGoalCommand(command: GitCommand): string { const q = (value: string) => /^[A-Za-z0-9._/@{}+-]+$/.test(value) ? value : `"${value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`; switch (command.kind) { case "add": return command.target.kind === "repositoryRoot" ? "git add ." : `git add ${command.target.paths.map(q).join(" ")}`; case "unstage": return `git restore --staged ${command.paths.map(q).join(" ")}`; case "commit": return command.message === undefined ? "git commit" : `git commit -m ${q(command.message)}`; case "switch": return `git switch ${command.create ? "-c " : ""}${q(command.branchName)}`; case "stashPush": return `git stash push${command.includeUntracked ? " -u" : ""}`; case "stashApply": return `git stash apply${command.stashIndex === undefined ? "" : ` stash@{${command.stashIndex}}`}`; case "stashPop": return `git stash pop${command.stashIndex === undefined ? "" : ` stash@{${command.stashIndex}}`}`; case "stashList": return "git stash list"; case "fetch": return `git fetch${command.remote ? ` ${q(command.remote)}` : ""}`; case "push": return command.target.kind === "default" ? "git push" : `git push${command.setUpstream ? " -u" : ""} ${q(command.target.remote)} ${q(command.target.branch)}`; case "pull": return `git pull${command.rebase ? " --rebase" : ""}${command.target.kind === "default" ? "" : ` ${q(command.target.remote)} ${q(command.target.branch)}`}`; case "merge": return `git merge ${q(command.branch)}`; case "rebase": return `git rebase ${q(command.upstream)}`; } }
