import { parseGitCommand } from "../commands/gitCommandParser";
import type { GitCommandParseResult } from "../domain/gitCommand";
import type { RepositoryState } from "../domain/repositoryState";
import type { SimulationEvent, SimulationNote, SimulationResult } from "../domain/simulation";
import { simulateGitCommand } from "../simulation/commandSimulator";
import type { AppViewStateStore } from "../domain/appViewStateStore";

export const COMMAND_INPUT_MAX_LENGTH = 4096;
export interface CommandPreviewAnalysis { readonly rawInput: string; readonly repositoryRoot: string; readonly basedOnStateVersion: number; readonly parse: GitCommandParseResult; readonly simulation?: SimulationResult; }
export interface CommandPreviewSession { readonly active: CommandPreviewAnalysis | null; readonly history: readonly CommandPreviewAnalysis[]; }
export const emptyCommandPreviewSession = (): CommandPreviewSession => ({ active: null, history: [] });

export function analyzeCommand(state: RepositoryState, rawInput: string): CommandPreviewAnalysis {
  const parse = rawInput.length > COMMAND_INPUT_MAX_LENGTH ? { kind: "parseFailure" as const, reason: `入力は${COMMAND_INPUT_MAX_LENGTH}文字以内にしてください。` } : parseGitCommand(rawInput);
  return { rawInput, repositoryRoot: state.repository.rootPath, basedOnStateVersion: state.stateVersion, parse, ...(parse.kind === "parsed" ? { simulation: simulateGitCommand(state, parse.command) } : {}) };
}
export function addAnalysis(session: CommandPreviewSession, analysis: CommandPreviewAnalysis): CommandPreviewSession { return { active: analysis, history: [analysis, ...session.history].slice(0, 5) }; }
export function previewIsStale(analysis: CommandPreviewAnalysis, state: RepositoryState | undefined): boolean { return !state || analysis.repositoryRoot !== state.repository.rootPath || analysis.basedOnStateVersion !== state.stateVersion; }

export class CommandPreviewController {
  constructor(private readonly viewState: AppViewStateStore<CommandPreviewSession>) {}
  analyze(state: RepositoryState, rawInput: string): void { const session = this.viewState.current.preview ?? emptyCommandPreviewSession(); this.viewState.set({ ...this.viewState.current, preview: addAnalysis(session, analyzeCommand(state, rawInput)) }); }
  recalculate(state: RepositoryState): void { const active = this.viewState.current.preview?.active; if (active) this.analyze(state, active.rawInput); }
  clear(): void { const session = this.viewState.current.preview; if (session?.active) this.viewState.set({ ...this.viewState.current, preview: { ...session, active: null } }); }
  selectHistory(index: number): void { const session = this.viewState.current.preview; const selected = session?.history[index]; if (session && selected) this.viewState.set({ ...this.viewState.current, preview: { ...session, active: selected } }); }
}

export interface CommandPreviewPresentation { readonly active: CommandPreviewAnalysis | null; readonly stale: boolean; readonly banner: boolean; readonly status: "none" | "parseFailure" | "unsupportedCommand" | "unsupportedOption" | "highRisk" | "supported" | "blocked" | "unsupported"; readonly sections: readonly PreviewSection[]; readonly map: PreviewMapOverlay | null; readonly history: readonly { readonly label: string; readonly stale: boolean }[]; readonly examples: readonly string[]; }
export interface PreviewSection { readonly title: "一言で何する" | "今のあなたの場合" | "変わるもの" | "変わらないもの" | "Git Map Preview" | "注意・前提"; readonly lines: readonly string[]; }
export interface PreviewPrediction { readonly id: string; readonly description: string; readonly parentCommitIds: readonly string[]; readonly basedOn?: { readonly kind: "existing" | "prediction"; readonly id: string }; readonly rewrittenFromCommitId?: string; }
export interface PreviewPointer { readonly kind: "branch" | "head"; readonly label: string; readonly target: { readonly kind: "existing"; readonly id: string } | { readonly kind: "prediction"; readonly id: string }; }
export interface PreviewMapOverlay { readonly workingTree: readonly string[]; readonly staging: readonly string[]; readonly stash: readonly string[]; readonly local: readonly string[]; readonly predictions: readonly PreviewPrediction[]; readonly pointers: readonly PreviewPointer[]; readonly remote: readonly string[]; readonly warnings: PreviewRegionNotes; readonly unknowns: PreviewRegionNotes; }
export interface PreviewRegionNotes { readonly workingTree: readonly string[]; readonly staging: readonly string[]; readonly stash: readonly string[]; readonly local: readonly string[]; readonly remote: readonly string[]; }

export function createCommandPreviewPresentation(session: CommandPreviewSession | null, state: RepositoryState | undefined): CommandPreviewPresentation {
  const active = session?.active ?? null; const stale = active ? previewIsStale(active, state) : false; const examples = state ? relatedExamples(state) : [];
  if (!active) return { active: null, stale: false, banner: false, status: "none", sections: [], map: null, history: session?.history.map((item) => ({ label: item.rawInput, stale: previewIsStale(item, state) })) ?? [], examples };
  const status = statusOf(active); const simulation = active.simulation;
  const sections: PreviewSection[] = [
    { title: "一言で何する", lines: [summary(active)] },
    { title: "今のあなたの場合", lines: [stale ? "このPreviewは変更前の状態を元にしています。" : situation(active)] },
    { title: "変わるもの", lines: simulation?.events.length ? simulation.events.map(eventText) : [status === "supported" ? "変化はありません。" : "Predictionは作成されていません。"] },
    { title: "変わらないもの", lines: unchanged(active) },
    { title: "Git Map Preview", lines: [stale ? "現在のFact Mapへは重ねません。" : mapText(active)] },
    { title: "注意・前提", lines: notices(active) },
  ];
  return { active, stale, banner: true, status, sections, map: stale || !simulation || simulation.kind !== "supported" ? null : overlay(simulation), history: session?.history.map((item) => ({ label: item.rawInput, stale: previewIsStale(item, state) })) ?? [], examples };
}

function statusOf(analysis: CommandPreviewAnalysis): CommandPreviewPresentation["status"] { if (analysis.parse.kind !== "parsed") return analysis.parse.kind; return analysis.simulation!.kind; }
function summary(analysis: CommandPreviewAnalysis): string { if (analysis.parse.kind === "parseFailure") return "入力を解析できません。"; if (analysis.parse.kind === "unsupportedCommand") return "このcommandはMVP対象外です。"; if (analysis.parse.kind === "unsupportedOption") return "このoptionはMVP対象外です。"; if (analysis.parse.kind === "highRisk") return "high risk commandを検出しました。"; const kind = analysis.parse.command.kind; return ({ add: "内容をStagingへ記録します。", unstage: "Stagingから外します。", commit: "Staging内容からcommitを作成します。", switch: "branchを切り替えます。", stashPush: "変更をStash Shelfへ退避します。", stashList: "Stash Shelfを確認します。", stashApply: "Stashを適用します。", stashPop: "Stashを適用後に削除します。", fetch: "Remote情報を取得します。", push: "local commitをRemoteへ送信します。", merge: "対象の履歴を統合します。", rebase: "local commitを別のbase上に再生成します。", pull: "fetchしてから統合します。" } satisfies Record<typeof kind, string>)[kind]; }
function situation(analysis: CommandPreviewAnalysis): string { if (analysis.parse.kind !== "parsed") return parseText(analysis.parse); const result = analysis.simulation!; return result.kind === "supported" ? "現在のFactを元に成功した場合のPreviewです。" : result.kind === "blocked" ? "現在のFactから、この操作は成立しないと判断できます。" : "この操作の詳細は現在のSimulatorでは扱いません。"; }
function unchanged(analysis: CommandPreviewAnalysis): readonly string[] { const simulation = analysis.simulation; if (!simulation) return ["Repositoryは変更されていません。"];
  const unknown = simulation.unknowns.length > 0 || simulation.warnings.length > 0;
  if (unknown) return ["Unknownまたは注意がある領域は、変わらないとは断定しません。", "Repositoryは変更されていません。"];
  return simulation.events.some((event) => event.kind === "noOp") ? ["commitやpointerは変わりません。", "Repositoryは変更されていません。"] : simulation.events.some((event) => event.kind === "headSymbolicRefChanged") ? ["branch pointerは動きません。", "Repositoryは変更されていません。"] : ["Factのcommit・branch・HEADはPreviewで置換しません。", "Repositoryは変更されていません。"];
}
function mapText(analysis: CommandPreviewAnalysis): string { const result = analysis.simulation; if (!result) return "Predictionはありません。"; if (result.kind !== "supported") return "future change overlayは作りません。"; return result.events.some((event) => event.kind === "noOp") ? "変更なしをMapに示します。" : "Fact MapにPrediction / Unknownを重ねます。"; }
function notices(analysis: CommandPreviewAnalysis): readonly string[] { if (analysis.parse.kind !== "parsed") return [parseText(analysis.parse), "このUIは実行しません。"]; const result = analysis.simulation!; return [...result.warnings.map(noteText), ...result.assumptions.map(noteText), ...result.unknowns.map(noteText), ...(result.risk === "caution" ? ["注意が必要な操作です。"] : []), ...(result.kind === "blocked" || result.kind === "unsupported" ? [reasonText(result.reason)] : []), "このUIは実行しません。"]; }
function reasonText(reason: string): string { switch (reason) { case "conflictsPresent": return "未解決のconflictがあるため、この操作は開始できません。"; case "nothingStaged": return "Stagingにcommitする変更がありません。"; case "unbornHead": return "まだ最初のcommitがないため、この操作は開始できません。"; case "operationNotNormal": return "別のGit処理の途中なので、この操作は扱いません。"; case "mergeCommitRebaseNotModeled": return "merge commitを含むrebaseの詳細はまだ扱いません。"; default: return "現在の状態では、この操作の詳細を安全に予測できません。"; } }
function parseText(parse: Exclude<GitCommandParseResult, { kind: "parsed" }>): string { switch (parse.kind) { case "parseFailure": return parse.reason; case "unsupportedCommand": return `${parse.commandName} はMVP対象外です。`; case "unsupportedOption": return `${parse.commandName} の ${parse.option} はMVP対象外です。`; case "highRisk": return `${parse.reason} 安全のため実行しません。`; } }
function eventText(event: SimulationEvent): string { switch (event.kind) { case "stagingReflected": return `${event.path}をStagingへ記録`; case "stagingUpdated": return `${event.path}のStaging内容を更新`; case "stagingRemoved": return `${event.path}をStagingから外す（Working Treeの内容は残る）`; case "stagedChangesCleared": return "新しいHEADとの差分としてStagingの変更が解消される"; case "commitCreated": return event.commit.kind === "newMergeCommit" ? "◌ NEW MERGE COMMITを生成" : event.commit.kind === "rewrittenCommit" ? `◌ commitを再生成（元 ${event.commit.originalCommitId.slice(0, 7)}）` : "◌ NEW COMMITを生成"; case "branchPointerMoved": return event.target.kind === "existingCommit" ? `${event.branchName} pointerを既存commitへ進める` : `${event.branchName} pointerをPredictionへ進める`; case "headSymbolicRefChanged": return `HEADを${event.branchName} branchへ向ける`; case "headBranchRelationRetained": return `HEADは${event.branchName} branchを参照したまま`; case "headDetachedMoved": return event.target.kind === "existingCommit" ? "detached HEADを既存commitへ進める" : "detached HEADをPredictionへ進める"; case "branchCreated": return `${event.branchName} branchを作成`; case "unbornSymbolicBranchChanged": return `unborn branchを${event.branchName}へ切替`; case "derivedRelationInvalidated": return event.relation === "comparison" ? "基準branchとの将来の差分は未確定です。" : "upstreamとの将来の差分は未確定です。"; case "stashCreated": return "Stash ShelfにPredictionを作成"; case "trackedChangesStashed": return "tracked changesをstash"; case "untrackedChangesStashed": return "untracked changesをstash"; case "stashChangesApplied": return "Stashを適用"; case "stashEntryRemovedAfterSuccessfulApply": return "成功した場合にStash entryを削除"; case "fetchRequested": return "fetchを要求"; case "remoteTrackingMayRefresh": return "remote-trackingは更新されるかもしれない"; case "pullFetchRequested": return "STEP 1 fetch"; case "pullIntegrationPlanned": return `STEP 2 integrate (${event.method === "rebase" ? "rebase" : "未確定"})`; case "pushRequested": return "local commit/refをRemoteへ送信試行"; case "branchUpstreamConfigured": return "upstream設定をPrediction"; case "noOp": return "変更なし"; } }
function noteText(note: SimulationNote): string { switch (note.code) { case "interactiveCommitMessageRequired": return "commit messageの入力が必要です。"; case "unknownPathScope": return `${note.path} が対象に含まれるかは未確定です。`; case "conflictResolutionNotModeled": return `${note.path} のconflict解消はPreviewしません。`; case "dirtySwitchMayFail": return "未commitの変更により切替が拒否される可能性があります。"; case "futureWorkingTreeAndIndexUnknown": return "将来のWorking TreeとIndexは未確定です。"; case "futureTrackingRelationUnknown": return "commit後のupstreamとのahead/behindは再確認するまで未確定です。"; case "branchNameAcceptedByGit": return `${note.branchName} が有効なbranch名として受け入れられる前提です。`; case "implicitRemoteGuessNotModeled": return "推測したRemote branchへの切替はPreviewしません。"; case "stashApplyMayConflict": return "Stashの適用でconflictが起こる可能性があります。"; case "stashTargetUnknown": return "適用するStashの内容は未確定です。"; case "liveRemoteStateUnknown": return "live Remoteの状態は未確認です。"; case "pushMayBeRejected": return "pushがRemoteに拒否される可能性があります。"; case "lastFetchedPushRelationMayReject": return "最後に取得した差分から、pushが拒否される可能性があります。"; case "defaultTargetUnknown": return "defaultの接続先は現在のFactから未確定です。"; case "pushSourceUnknown": return `${note.branchName} の送信元commitは未確定です。`; case "upstreamConfigurationUnknown": return "upstream設定が成功するかは未確定です。"; case "stashApplyDoesNotGuaranteeStagedness": return "適用後にStagingへ戻る内容は未確定です。"; case "uncommittedChangesNotPushed": return "未commitの変更はpushされません。"; case "targetResolutionUnknown": return `${note.operand} を現在のFactから解決できません。`; case "historyRelationUnknown": return "bounded historyだけでは履歴関係を確定できません。"; case "mergeMayConflict": return "mergeでconflictが起こる可能性があります。"; case "rebaseMayConflict": return "rebaseでconflictが起こる可能性があります。"; case "dirtyMergeMayFail": return "未commitの変更によりmergeが拒否される可能性があります。"; case "dirtyRebaseMayBeRejected": return "未commitの変更によりrebaseが拒否される可能性があります。"; case "rebaseReplayRangeUnknown": return "rebaseで再生成する範囲は未確定です。"; case "fetchedTipUnknown": return "fetch後のtipは外部結果のため未確定です。"; case "pullIntegrationMethodUnknown": return "通常pullの統合方法は未確定です。"; case "pullIntegrationOutcomeUnknown": return "統合結果は未確定です。"; case "pullMayConflict": return "統合時にconflictが起こる可能性があります。"; } }
function overlay(result: SimulationResult): PreviewMapOverlay { const workingTree: string[] = []; const staging: string[] = []; const stash: string[] = []; const local: string[] = []; const remote: string[] = []; const warnings: Record<keyof PreviewRegionNotes, string[]> = { workingTree: [], staging: [], stash: [], local: [], remote: [] }; const unknowns: Record<keyof PreviewRegionNotes, string[]> = { workingTree: [], staging: [], stash: [], local: [], remote: [] }; const pointers: PreviewPointer[] = []; const predictions: PreviewPrediction[] = []; let previousPrediction: string | undefined;
  for (const event of result.events) { const text = eventText(event); if (event.kind === "stagingReflected" || event.kind === "stagingUpdated" || event.kind === "stagingRemoved") { workingTree.push(text); staging.push(text); } else if (event.kind === "stagedChangesCleared") staging.push(text); else if (event.kind === "stashCreated" || event.kind === "trackedChangesStashed" || event.kind === "untrackedChangesStashed" || event.kind === "stashChangesApplied" || event.kind === "stashEntryRemovedAfterSuccessfulApply") stash.push(text); else if (event.kind === "fetchRequested" || event.kind === "pushRequested" || event.kind === "pullFetchRequested" || event.kind === "pullIntegrationPlanned" || event.kind === "remoteTrackingMayRefresh") remote.push(text); else if (event.kind === "commitCreated") { const id = `prediction-${predictions.length + 1}`; const commit = event.commit; predictions.push({ id, description: commit.kind === "newMergeCommit" ? "NEW MERGE COMMIT" : commit.kind === "rewrittenCommit" ? `再生成されたcommit（元 ${commit.originalCommitId.slice(0, 7)}）` : "NEW COMMIT", parentCommitIds: commit.kind === "rewrittenCommit" ? [] : commit.parentCommitIds, ...(commit.kind === "rewrittenCommit" ? { rewrittenFromCommitId: commit.originalCommitId, basedOn: commit.basedOn.kind === "existingCommit" ? { kind: "existing" as const, id: commit.basedOn.id } : { kind: "prediction" as const, id: previousPrediction ?? commit.basedOn.originalCommitId } } : {}) }); previousPrediction = id; } else if (event.kind === "branchPointerMoved") { const target = event.target.kind === "existingCommit" ? { kind: "existing" as const, id: event.target.id } : { kind: "prediction" as const, id: previousPrediction ?? "prediction-1" }; pointers.push({ kind: "branch", label: event.branchName, target }); local.push(text); } else if (event.kind === "headDetachedMoved") { const target = event.target.kind === "existingCommit" ? { kind: "existing" as const, id: event.target.id } : { kind: "prediction" as const, id: previousPrediction ?? "prediction-1" }; pointers.push({ kind: "head", label: "HEAD", target }); local.push(text); } else if (event.kind === "headSymbolicRefChanged" || event.kind === "headBranchRelationRetained" || event.kind === "branchCreated" || event.kind === "unbornSymbolicBranchChanged") local.push(text); }
  for (const note of result.warnings) warnings[noteRegion(note)].push(noteText(note));
  for (const note of result.unknowns) unknowns[noteRegion(note)].push(noteText(note));
  return { workingTree, staging, stash, local, predictions, pointers, remote, warnings, unknowns }; }
function noteRegion(note: SimulationNote): keyof PreviewRegionNotes { switch (note.code) { case "unknownPathScope": case "conflictResolutionNotModeled": case "futureWorkingTreeAndIndexUnknown": case "uncommittedChangesNotPushed": return "workingTree"; case "stashTargetUnknown": case "stashApplyDoesNotGuaranteeStagedness": case "stashApplyMayConflict": return "stash"; case "futureTrackingRelationUnknown": case "implicitRemoteGuessNotModeled": case "liveRemoteStateUnknown": case "pushMayBeRejected": case "lastFetchedPushRelationMayReject": case "defaultTargetUnknown": case "upstreamConfigurationUnknown": case "fetchedTipUnknown": case "pullIntegrationMethodUnknown": case "pullIntegrationOutcomeUnknown": case "pullMayConflict": return "remote"; case "interactiveCommitMessageRequired": case "dirtySwitchMayFail": case "branchNameAcceptedByGit": case "pushSourceUnknown": case "targetResolutionUnknown": case "historyRelationUnknown": case "mergeMayConflict": case "rebaseMayConflict": case "dirtyMergeMayFail": case "dirtyRebaseMayBeRejected": case "rebaseReplayRangeUnknown": return "local"; } }
function relatedExamples(state: RepositoryState): readonly string[] { const examples: string[] = []; if (state.workingTree.unstaged.length || state.workingTree.untracked.length) examples.push("git add ."); if (state.workingTree.staged.length) examples.push('git commit -m "message"'); if (state.stash.kind === "available" && state.stash.value.length) examples.push("git stash list"); if (state.upstream.kind === "available" && state.upstream.value.remoteName !== ".") examples.push(`git fetch ${state.upstream.value.remoteName}`); const branch = state.localBranches.find((item) => state.currentLocation.kind !== "branch" || item.name !== state.currentLocation.branchName); if (branch) examples.push(`git switch ${branch.name}`); return examples.slice(0, 4); }
