import { escapeHtml, renderOverviewHtml } from "./overviewHtmlRenderer";
import { createOverviewPresentation } from "./overviewPresentation";
import type { GitMapItem, GitMapPresentation } from "./gitMapPresentation";
import type { CommitGraphPresentation } from "./commitGraphPresentation";

export function renderGitMapHtml(presentation: GitMapPresentation, nonce: string): string {
  const content = presentation.status === "available" ? availableMap(presentation) : `<p class="message"${presentation.unavailableReason ? ` title="${escapeHtml(presentation.unavailableReason)}"` : ""}>${escapeHtml(presentation.message ?? "")}</p>`;
  return `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8" /><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Git Bearings: Git Map</title><style nonce="${nonce}">
.local-ref { fill:var(--vscode-editor-background); stroke:var(--vscode-foreground); stroke-width:1.5; } .ref-line,.head-line { fill:none; stroke:var(--vscode-foreground); stroke-width:1.5; } .head-label { fill:var(--vscode-foreground); font-size:11px; font-weight:700; } .remote-tracking-box,.remote-tracking-line { fill:none; stroke:var(--vscode-descriptionForeground); stroke-width:1.5; stroke-dasharray:4 3; } .remote-tracking-hidden { display:none; } .unborn-head { font-weight:700; } .unborn-branch { border:1px solid var(--vscode-foreground); border-radius:4px; padding:2px 6px; } .fact-state { border-left:2px solid var(--vscode-foreground); padding-left:8px; } .unknown-state { border:1px dashed var(--vscode-descriptionForeground); padding:5px 8px; } .unknown-symbol { font-weight:700; margin-right:6px; } .warning-state { border:1px solid var(--vscode-notificationsWarningIcon-foreground); border-radius:3px; padding:5px 8px; } .warning-symbol { font-weight:700; margin-right:6px; } .selected-state { outline:2px solid var(--vscode-focusBorder); outline-offset:3px; } .related-state { outline:1px dashed var(--vscode-focusBorder); outline-offset:2px; } .prediction-node { fill:none; stroke:var(--vscode-descriptionForeground); stroke-width:2; stroke-dasharray:4 3; } .prediction-label { fill:var(--vscode-descriptionForeground); font-size:10px; font-weight:700; }
:root { color: var(--vscode-foreground); font-family: var(--vscode-font-family); } body { margin: 0; padding: 18px; } h1 { font-size: 1.2em; margin: 0 0 5px; } h2 { margin: 0 0 8px; font-size: .8em; letter-spacing: .1em; color: var(--vscode-descriptionForeground); } p { margin: 0; } .repository,.muted,.message { color: var(--vscode-descriptionForeground); overflow-wrap: anywhere; } .operation { margin: 14px 0; font-weight:700; } .surface { margin-top: 18px; max-width: 960px; } .region { padding: 14px 0; border-top: 1px solid var(--vscode-panel-border); } .flow { margin-left: 18px; color: var(--vscode-descriptionForeground); font-weight: 700; } dl { margin: 0; } dl div { display:grid; grid-template-columns: minmax(120px,auto) minmax(0,1fr); gap: 10px; margin: 4px 0; } dt { color: var(--vscode-descriptionForeground); } dd { margin: 0; overflow-wrap: anywhere; } .staging { padding-left: 10px; border-left: 2px solid var(--vscode-panel-border); } .stash-shelf { float:right; margin:0 0 8px 12px; border:1px solid var(--vscode-panel-border); border-radius:3px; padding:5px 8px; } .graph-scroll { overflow-x: auto; padding: 8px 0; } .commit-graph { display:block; min-width: 520px; } .graph-edge { fill:none; stroke:var(--vscode-panel-border); stroke-width:2; } .graph-node { fill:var(--vscode-editor-background); stroke:var(--vscode-foreground); stroke-width:2; } .graph-node-current { stroke:var(--vscode-focusBorder); stroke-width:3; } .graph-node-base { fill:var(--vscode-textLink-foreground); } .graph-node-selected { stroke-width:4; stroke-dasharray:none; } .graph-node-related { stroke-width:3; stroke-dasharray:3 2; } .graph-text { fill:var(--vscode-foreground); font-size:12px; } .graph-subject { fill:var(--vscode-descriptionForeground); } .graph-role { fill:var(--vscode-descriptionForeground); font-size:10px; font-weight:700; } .graph-omission { fill:var(--vscode-descriptionForeground); font-size:11px; } .remote { margin-top: 10px; padding-left: 10px; border-left: 2px solid var(--vscode-panel-border); } details { border-top: 1px solid var(--vscode-panel-border); margin-top: 18px; padding-top: 12px; } summary { cursor: pointer; } .overview { margin-top: 12px; } .overview-section { border-top: 1px solid var(--vscode-panel-border); padding: 10px 0; } .overview-section h3 { margin: 0 0 7px; font-size: .95em; } .overview-repository { display:none; } .overview-message,.overview-meaning { color: var(--vscode-descriptionForeground); } .overview-operation { border-left: 3px solid var(--vscode-notificationsWarningIcon-foreground); padding-left: 8px; font-weight:700; } @media (prefers-reduced-motion: reduce) { *,*::before,*::after { animation:none !important; transition:none !important; } }
</style></head><body><h1>Git Bearings: Git Map</h1>${presentation.repository ? `<p class="repository">${escapeHtml(presentation.repository)}</p>` : ""}${presentation.operationBanner ? `<p class="operation warning-state"><span class="warning-symbol">!</span>${escapeHtml(presentation.operationBanner)}</p>` : ""}${content}<script nonce="${nonce}">const v=acquireVsCodeApi();document.addEventListener('click',e=>{const t=e.target.closest('[data-selection]');if(t)v.postMessage({type:'select',selection:JSON.parse(t.dataset.selection)});});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('[data-selection]')){e.preventDefault();e.target.closest('[data-selection]').click();}});</script></body></html>`;
}

function availableMap(presentation: GitMapPresentation): string {
  const remote = presentation.remoteMessage ? (presentation.remoteUnavailableReason ? unknown({ label: presentation.remoteMessage, message: "" }, presentation.remoteUnavailableReason) : `<p class="muted">${escapeHtml(presentation.remoteMessage)}</p>`) : presentation.remotes.map((item) => `<section class="remote fact-state"${selectionAttr({ kind: "remote", remoteName: item.name })}><strong>${escapeHtml(item.name)}</strong>${facts(item.facts)}${unknown(item.liveRemote)}</section>`).join("");
  return `<main class="surface" aria-label="Git Map"><section class="region fact-state"><h2>WORKING TREE</h2>${workingTree(presentation.workingTree)}</section><p class="flow" aria-hidden="true">↓ git add：内容をStagingへ記録</p><section class="region staging fact-state"><h2>STAGING</h2>${facts([{ label: "Staged", value: String(presentation.staging.stagedCount) }])}</section>${stash(presentation.stash)}<p class="flow" aria-hidden="true">↓ commit：Staging内容からcommitを作成</p><section class="region"><h2>LOCAL REPOSITORY</h2>${renderCommitGraph(presentation.graph)}</section><section class="region"><h2>REMOTE</h2>${remote}<section class="remote"${presentation.upstreamUnavailableReason ? ` title="${escapeHtml(presentation.upstreamUnavailableReason)}"` : ""}>${facts(presentation.upstream)}</section><p class="muted">Remote情報はローカルGitが最後に取得した情報です。live Remoteの状態ではありません。</p></section><details><summary>Detail</summary>${renderOverviewHtml(createOverviewPresentation(presentation.detailSnapshot))}</details></main>`;
}

function renderCommitGraph(graph: CommitGraphPresentation): string {
  if (graph.kind === "unborn") return `<p class="unborn-head">HEAD<br />↓<br /><span class="unborn-branch">[ ${escapeHtml(graph.unbornBranch ?? "")} ]</span></p><p class="muted">${escapeHtml(graph.message ?? "")}</p>`;
  if (graph.kind !== "graph") return `<p class="muted">${escapeHtml(graph.message ?? "")}</p>`;
  const edges = graph.edges.map((edge) => `<path class="graph-edge" d="M ${edge.parentX + 7} ${edge.parentY} C ${edge.parentX + 42} ${edge.parentY}, ${edge.childX - 42} ${edge.childY}, ${edge.childX - 7} ${edge.childY}" />`).join("");
  const omissions = graph.omissions.map((omission) => `<text class="graph-omission" x="${omission.x}" y="${omission.y + 4}" text-anchor="middle">… 履歴を省略 …</text>`).join("");
  const refs = graph.localBranches.map((ref) => `<g class="local-branch-ref${ref.visualState ? ` ${ref.visualState}-state` : ""}"${selectionAttr({ kind: "branch", branchName: ref.label })}><path class="ref-line" d="M ${ref.connector.fromX} ${ref.connector.fromY} L ${ref.connector.toX} ${ref.connector.toY}" /><rect class="local-ref" x="${ref.bounds.left}" y="${ref.bounds.top}" width="${ref.bounds.width}" height="${ref.bounds.height}" rx="5" /><text class="graph-text" x="${ref.x}" y="${ref.y + 2}" text-anchor="middle">${escapeHtml(ref.label)}</text></g>`).join("");
  const tracking = graph.remoteTrackingRefs.map((ref) => `<g class="remote-tracking-ref${ref.revealed ? "" : " remote-tracking-hidden"}"><path class="remote-tracking-line" d="M ${ref.connector.fromX} ${ref.connector.fromY} L ${ref.connector.toX} ${ref.connector.toY}" /><rect class="remote-tracking-box" x="${ref.bounds.left}" y="${ref.bounds.top}" width="${ref.bounds.width}" height="${ref.bounds.height}" rx="2" /><text class="graph-text" x="${ref.x}" y="${ref.y + 2}" text-anchor="middle">remote-tracking: ${escapeHtml(ref.label)}</text></g>`).join("");
  const head = graph.head ? `<g class="head-pointer${graph.head.visualState ? ` ${graph.head.visualState}-state` : ""}"${selectionAttr({ kind: "head" })}><path class="head-line" d="M ${graph.head.x} ${graph.head.y + 8} L ${graph.head.x} ${graph.head.targetY}" /><text class="head-label" x="${graph.head.x}" y="${graph.head.y}" text-anchor="middle">HEAD</text></g>` : "";
  const predictions = (graph.predictionCommits ?? []).map((node) => `<g class="prediction-commit${node.visualState ? ` ${node.visualState}-state` : ""}"><circle class="prediction-node" cx="${node.x}" cy="${node.y}" r="7" /><text class="prediction-label" x="${node.x + 13}" y="${node.y - 4}">${node.label}</text><text class="prediction-label" x="${node.x + 13}" y="${node.y + 12}">◌ ${node.description}</text></g>`).join("");
  const nodes = graph.nodes.map((node) => {
    const roles = [
      ...(node.roles.includes("base") ? ["BASE"] : []),
      ...(node.roles.includes("mergeBase") ? ["COMMON ANCESTOR"] : []),
    ].join(" ");
    return `<g class="fact-commit${node.visualState ? ` ${node.visualState}-state` : ""}"${selectionAttr({ kind: "commit", commitId: node.commitId })}><circle class="graph-node${node.roles.includes("current") ? " graph-node-current" : ""}${node.roles.includes("base") ? " graph-node-base" : ""}${node.visualState ? ` graph-node-${node.visualState}` : ""}" cx="${node.x}" cy="${node.y}" r="7" /><text class="graph-text" x="${node.x + 13}" y="${node.y - 5}">${escapeHtml(node.shortId)}</text><text class="graph-text graph-subject" x="${node.x + 13}" y="${node.y + 12}">${escapeHtml(node.subject)}</text>${roles ? `<text class="graph-role" x="${node.x}" y="${node.y - 14}" text-anchor="middle">${roles}</text>` : ""}</g>`;
  }).join("");
  return `<div class="graph-scroll"><svg class="commit-graph" role="img" aria-label="Commit Graph: old to new" width="${graph.width}" height="${graph.height}" viewBox="0 0 ${graph.width} ${graph.height}" xmlns="http://www.w3.org/2000/svg">${edges}${omissions}${refs}${tracking}${head}${nodes}${predictions}</svg></div>`;
}

function workingTree(tree: import("./gitMapPresentation").WorkingTreePresentation): string {
  return facts([{ label: "状態", value: tree.kind === "clean" ? "clean" : "changesあり" }, { label: "Unstaged", value: String(tree.unstagedCount) }, { label: "Modified", value: String(tree.modifiedCount) }, { label: "Untracked", value: String(tree.untrackedCount) }, { label: "Conflicts", value: String(tree.conflictsCount) }]);
}

function stash(value: import("./gitMapPresentation").StashPresentation): string {
  if (value.kind === "none") return "";
  if (value.kind === "unavailable") return `<aside class="stash-unknown unknown-state" title="${escapeHtml(value.reason)}"><span class="unknown-symbol">?</span>Stash情報を取得できません</aside>`;
  return `<aside class="stash-shelf fact-state">Stash Shelf · ${value.count}件</aside>`;
}

function unknown(value: import("./gitMapPresentation").GitMapUnknown, reason?: string): string { return `<p class="unknown-state"${reason ? ` title="${escapeHtml(reason)}"` : ""}><span class="unknown-symbol">?</span>${escapeHtml(value.label)}${value.message ? `：${escapeHtml(value.message)}` : ""}</p>`; }

function facts(items: readonly GitMapItem[]): string { return `<dl>${items.map((item) => `<div><dt>${escapeHtml(item.label)}</dt><dd>${escapeHtml(item.value)}</dd></div>`).join("")}</dl>`; }
function selectionAttr(selection: unknown): string { return ` data-selection="${escapeHtml(JSON.stringify(selection))}" tabindex="0" role="button"`; }
