import { escapeHtml, renderOverviewHtml } from "./overviewHtmlRenderer";
import { createOverviewPresentation } from "./overviewPresentation";
import type { GitMapItem, GitMapPresentation } from "./gitMapPresentation";

export function renderGitMapHtml(presentation: GitMapPresentation, nonce: string): string {
  const content = presentation.status === "available" ? availableMap(presentation) : `<p class="message"${presentation.unavailableReason ? ` title="${escapeHtml(presentation.unavailableReason)}"` : ""}>${escapeHtml(presentation.message ?? "")}</p>`;
  return `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8" /><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}';" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Git Bearings: Git Map</title><style nonce="${nonce}">
:root { color: var(--vscode-foreground); font-family: var(--vscode-font-family); } body { margin: 0; padding: 18px; max-width: 760px; } h1 { font-size: 1.2em; margin: 0 0 5px; } h2 { margin: 0 0 8px; font-size: .8em; letter-spacing: .1em; color: var(--vscode-descriptionForeground); } p { margin: 0; } .repository,.muted,.message { color: var(--vscode-descriptionForeground); overflow-wrap: anywhere; } .operation { border-left: 3px solid var(--vscode-notificationsWarningIcon-foreground); padding-left: 8px; margin: 14px 0; font-weight: 700; } .surface { margin-top: 18px; } .region { padding: 14px 0; border-top: 1px solid var(--vscode-panel-border); } .flow { margin-left: 18px; color: var(--vscode-descriptionForeground); font-weight: 700; } dl { margin: 0; } dl div { display:grid; grid-template-columns: minmax(120px,auto) minmax(0,1fr); gap: 10px; margin: 4px 0; } dt { color: var(--vscode-descriptionForeground); } dd { margin: 0; overflow-wrap: anywhere; } .staging { padding-left: 10px; border-left: 2px solid var(--vscode-panel-border); } .remote { margin-top: 10px; padding-left: 10px; border-left: 2px solid var(--vscode-panel-border); } details { border-top: 1px solid var(--vscode-panel-border); margin-top: 18px; padding-top: 12px; } summary { cursor: pointer; } .overview { margin-top: 12px; } .overview-section { border-top: 1px solid var(--vscode-panel-border); padding: 10px 0; } .overview-section h3 { margin: 0 0 7px; font-size: .95em; } .overview-repository { display:none; } .overview-message,.overview-meaning { color: var(--vscode-descriptionForeground); } .overview-operation { border-left: 3px solid var(--vscode-notificationsWarningIcon-foreground); padding-left: 8px; font-weight: 700; }
</style></head><body><h1>Git Bearings: Git Map</h1>${presentation.repository ? `<p class="repository">${escapeHtml(presentation.repository)}</p>` : ""}${presentation.operationBanner ? `<p class="operation">${escapeHtml(presentation.operationBanner)}</p>` : ""}${content}</body></html>`;
}

function availableMap(presentation: GitMapPresentation): string {
  return `<main class="surface" aria-label="Git Map"><section class="region"><h2>WORKING TREE</h2>${facts(presentation.workingTree)}</section><p class="flow" aria-hidden="true">↓ add</p><section class="region staging"><h2>STAGING</h2>${facts([presentation.staging])}</section><p class="flow" aria-hidden="true">↓ commit</p><section class="region"><h2>LOCAL REPOSITORY</h2>${facts(presentation.local)}</section><section class="region"><h2>REMOTE</h2>${presentation.remoteMessage ? `<p class="muted"${presentation.remoteUnavailableReason ? ` title="${escapeHtml(presentation.remoteUnavailableReason)}"` : ""}>${escapeHtml(presentation.remoteMessage)}</p>` : presentation.remotes.map((remote) => `<section class="remote"><strong>${escapeHtml(remote.name)}</strong>${facts(remote.facts)}</section>`).join("")}<section class="remote"${presentation.upstreamUnavailableReason ? ` title="${escapeHtml(presentation.upstreamUnavailableReason)}"` : ""}>${facts(presentation.upstream)}</section><p class="muted">Remote情報はローカルGitが最後に取得した情報です。live Remoteの状態ではありません。</p></section><details><summary>Detail</summary>${renderOverviewHtml(createOverviewPresentation(presentation.detailSnapshot))}</details></main>`;
}

function facts(items: readonly GitMapItem[]): string { return `<dl>${items.map((item) => `<div><dt>${escapeHtml(item.label)}</dt><dd>${escapeHtml(item.value)}</dd></div>`).join("")}</dl>`; }
